language: cpp
sudo: true

matrix:
  include:
    - name: "gcc 8"
      env: MATRIX_ENV="CC=gcc-8 CXX=g++-8"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
    - name: "gcc 7"
      env: MATRIX_ENV="CC=gcc-7 CXX=g++-7"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
    - name: "gcc 6"
      env: MATRIX_ENV="CC=gcc-6 CXX=g++-6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
    - name: "clang 6"
      env: MATRIX_ENV="CC=clang-6.0 CXX=clang++-6.0"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-6.0
          packages:
            - libstdc++-8-dev
            - clang-6.0

env:
  global:
    - MAKEFLAGS="-j 2"  # parallelize compilation process

before_install: eval "${MATRIX_ENV}"

script:
  - cmake . -DCMAKE_BUILD_TYPE=Debug
  - make all
